src/bin/add.rs
src/bin/unsquashfs.rs
src/squashfs.rs
src/tree.rs

* Add correct header permissions to the Dir Node
* Apply to unsquashfs

Apply dir permissions

---

Cargo.toml
src/squashfs.rs
tests/test.rs

* Use found file header in directory

Fix file permissions

---

tests/test.rs

This will make the tests more data driven and easier to change

Make all tests use full_test function

---

CHANGELOG.md
Cargo.toml
README.md
src/bin/add.rs
src/filesystem.rs
tests/common/mod.rs
tests/mutate.rs
tests/test.rs

- Add `Filesystem::push_file(..)` for adding a file, as well as the dirs for the path
- Add `Filesystem::mut_file(..)` for mutating a file at a path already in the filesystem

Add push_file and mut_file to filesystem

---

CHANGELOG.md
src/filesystem.rs
src/squashfs.rs

* Add mod_time from Squashfs to Filesystem used in creation of new image with to_bytes(..)

Add mod_time to Filesystem

---

CHANGELOG.md
README.md
src/filesystem.rs
tests/mutate.rs
tests/test.rs

Add `Filesystem::from_reader(..)` and `Filesystem::from_reader_with_offset(..)` which calls `Squashfs::from_reader(..)` and `Squashfs::from_reader_with_offset(..)`, and `Squashfs::into_filesystem(..)`.

Add Filesystem::from_reader(..)

---

src/bin/unsquashfs.rs
src/filesystem.rs
src/squashfs.rs
src/tree.rs
tests/mutate.rs
tests/test.rs

* Add support for reading and writing block and char devices
* Add panic if a type of file isn't supported within into_filesystem
* Don't add support to unsquashfs yet

Add Block and Char device support

---

tests/common/mod.rs
tests/test.rs

* Add test with one char device /dev/console as console
* Add test that only checks the file listing, since we can't extract char device if we aren't root

Add char device test

---

src/squashfs.rs

Change inode_key to i32 before u32

---

src/filesystem.rs
src/squashfs.rs
tests/test.rs

* Fix bug in char/block device that removed the path

Add TP-Link ER605 testing

---

CHANGELOG.md
src/filesystem.rs
src/tree.rs

DRAFT: Correctly set directory permissions

---

CHANGELOG.md
README.md
src/bin/add.rs
src/bin/unsquashfs.rs

Improve and change `unsquashfs` and `add` cli to match `squashfs-tools/unsquashfs` cli

Improve and change unsquashfs and add cli

---

CHANGELOG.md
src/bin/unsquashfs.rs
src/filesystem.rs
src/reader.rs
src/squashfs.rs

Add filesystem functions + use `Read + Seek` + Change `Path` -> `Dir`

---

CHANGELOG.md
src/filesystem.rs

Fix inode_count by removing one from inode

Fix inode_count

---

src/bin/unsquashfs.rs
src/dir.rs
src/filesystem.rs
src/squashfs.rs

Represent filenames as PathBuf instead of String

---

src/bin/unsquashfs.rs

- Remove call of create_dir_all in File and Symlink, as the directory will already be created
- Write permissions in both file and symlink

Only Dir writes directory with permissions

---

Cargo.toml
src/bin/unsquashfs.rs

- Add nix for libc calls
- Use mknod to create block/char files when we can

Add char and block device extraction

---

src/bin/unsquashfs.rs

- Hide normal output from unsquashfs without --info flag

Add --info flag

---

src/data.rs

- Use data.finalize() each time to store the fragment bytes
- Replace with_capacity with clear() to remove realloc
- Only store fragment compressed if size if smaller. This really only matter for very high entropy data such as from /dev/random.

Use data.finalize(), only save compressed fragment when smaller

---

src/bin/unsquashfs.rs
src/compressor.rs
src/data.rs
src/filesystem.rs
src/fragment.rs
src/inode.rs
src/metadata.rs
src/reader.rs
src/squashfs.rs
src/tree.rs
tests/mutate.rs

Have the objective to speedup the lib by implementing something like https://github.com/wcampbell0x2a/backhand/issues/130

Just copy unmodified files

---

.github/workflows/main.yml
Cargo.toml
tests/test.rs

- Don't test ex6100v2, as I can't de-compress
- Don't test tplink_ax1800, as I can't de-compress

Add xz-static feature to build with xz static

---

CHANGELOG.md
README.md
src/bin/replace.rs

- Add replace binary, much like add but replaces the file
- Add -o, --output to add binary
closes #154

Add replace binary

---

CHANGELOG.md
src/squashfs.rs

- This should actually be mib instead of mb, we are check for more then 0x100000

Fix invalid block_size check

---

src/filesystem/writer.rs
src/reader.rs
src/squashfs.rs
tests/common/mod.rs
tests/test.rs

https://github.com/wcampbell0x2a/backhand/pull/169 with tests

Fix Read/Write with offset initialization

---

README.md
src/bin/add.rs
src/filesystem/node.rs
src/filesystem/writer.rs

- Read file details in add binary
- Add --mtime, --gid, --uid, --mode for overriding the read file details
Closes #180, #177

add: Read file details and use in filesystem; add cli

---

CHANGELOG.md
src/compressor.rs
src/filesystem/writer.rs

- [Add FilesystemWriter::options(..)](https://github.com/wcampbell0x2a/backhand/commit/7dfacb610f5bd0654299b64738bab689a866b308)
-  [Condense Gzip Compressor logic in compress()](https://github.com/wcampbell0x2a/backhand/commit/721cc5bfc8d6c28de664e7648aa5663bce162694)
- [Add FilesystemWriter::set_no_padding()](https://github.com/wcampbell0x2a/backhand/commit/849aea4bb7c063ff5cab918ba06576127abf01ba)

Add filesystemWriter::add_no_padding

---

src/bin/unsquashfs.rs
src/filesystem/reader.rs
src/lib.rs
src/reader.rs
src/squashfs.rs
src/tree.rs

~~WIP: I think I will make the allocation a part of FilesystemReader, but this will do for now.~~

Reduce allocations in FilesystemReaderFile

---

tests/bin.rs
tests/common/mod.rs
tests/test.rs

Compare the output of squashfs-tools/unsquashfs vs our own
See #88

Add test for unsquashfs

---

README.md
benches/benchmark.rs
src/bin/add.rs
src/bin/replace.rs
src/bin/unsquashfs.rs
src/filesystem/reader.rs
src/filesystem/writer.rs
src/lib.rs
src/reader.rs
src/squashfs.rs
tests/mutate.rs
tests/non_standard.rs
tests/raw.rs
tests/test.rs

Buffering read/write can speed up tests significantly.

Use Buffered Read/Write

---

src/bin/unsquashfs.rs
src/squashfs.rs

* Only parse Superblock and Compression options
* Use this for unsquashfs --stat

Add Squashfs::superblock_and_compression_options(..)

---

src/bin/unsquashfs.rs

unsquashfs: Report decompression algorithms available

---

Cargo.lock
Cargo.toml
README.md
src/bin/unsquashfs.rs

- --completions will emit shell completions for multiple shells

unsquashfs: Add --completions

---

src/metadata.rs

Also made uncompressed data a `VecDeque` to avoid reallocation when the data is extract with `drain`

Only store the compressed metadata if resulting in smaller size

---

src/filesystem/reader.rs
src/filesystem/writer.rs

Decrease of around 1MB for some images. Not making assumptions about the size of the data in the image

Decrease memory usage in reader/writer

---

.github/workflows/binaries.yml

ci: Add semver check

---

Cargo.lock
Cargo.toml
benches/benchmark.rs
tests/add.rs
tests/mutate.rs
tests/raw.rs
tests/replace.rs
tests/test.rs

- Use test-assets/replace-curl-ureq
- Use https on wcampbell.dev

test: Use test-assets branch: replace-curl-ureq

---

src/dir.rs
src/squashfs.rs

Fix https://github.com/wcampbell0x2a/backhand/discussions/270 and as a bonus remove a unnecessary clone.

DirEntry only allow root and simple filenames

---

src/bin/unsquashfs.rs

bins: Fix macOS builds

---

src/compressor.rs
src/data.rs
src/entry.rs
src/filesystem/writer.rs
src/metadata.rs
src/reader.rs
src/squashfs.rs

- This messes with the code coverage, and in general doesn't provide much now that this library is more "written"

bh: Remove tracing::instrument

---

tests/non_standard.rs

- These were causing random test failure on the CI, hopefully this fixes it

Move to using self-hosted custom images

---

.github/workflows/pull_request.yml

- Replace label activation with dependencies
- Remove commit user info override

ci: Fix changelog gen

---

backhand-cli/src/bin/unsquashfs.rs

unsquashfs: Fix red_bold color

---

Cargo.lock
Cargo.toml
backhand-cli/Cargo.toml
backhand/Cargo.toml
backhand/src/lib.rs

Add document-features, that will automatically document the features
Add comments to features, in a way supported by other tooling such as libs.rs
Add other docs.rs flags
Closes #325

backhand: Add optional document-features

---

.github/workflows/binaries.yml
.github/workflows/coverage.yml
CHANGELOG.md
README.md
backhand-cli/Cargo.toml
backhand-test/tests/add.rs
backhand-test/tests/common/mod.rs
backhand-test/tests/replace.rs
backhand-test/tests/unsquashfs.rs

bins: Rename bins to *-backhand

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
backhand-cli/Cargo.toml
backhand/Cargo.toml
backhand/src/lib.rs

Fix README manifest link

---

CHANGELOG.md
Cargo.toml

Enable overflow checks for dist and release profiles

---

BENCHMARK.md
bench.bash

Update benchmark script to have spaces in between results
Update benchmakr to have smaller names

Update benchmark script

---

.github/workflows/benchmark.yml
backhand/benches/benchmark.rs

- [ci: Use new criterion-compare-action before cmd](https://github.com/wcampbell0x2a/backhand/commit/2d87afbb94031d9616ca14f39263ca005c12cef7)
- [bench: Increase sample size of unsquashfs](https://github.com/wcampbell0x2a/backhand/commit/9dcbc58fa1c4f94140c9b527ac44229f379bbce6)

Use custom critcmp before cmd

---

backhand/Cargo.toml

Disable RUST_LOG for release binaries

---

backhand/src/error.rs
backhand/src/reader.rs
backhand/src/squashfs.rs

Add try_reserve to Inode parsing

---

.github/workflows/pull_request.yml

Reverts wcampbell0x2a/backhand#467

Revert "ci: Remove if for changelog generation"

---

.github/workflows/pull_request.yml

Reverts wcampbell0x2a/backhand#480

Revert "Revert "ci: Remove if for changelog generation""

---

backhand-test/tests/raw.rs

* Fix test being incorrect, because neither unsquashfs nor unsquashfs-backhand set the uid or gid if not started as a root process
* Add unsquashfs -lln test to make sure we set it correctly now

test: Fix raw uid and gid matching control squashfs

---

.github/workflows/binaries.yml
.github/workflows/main.yml

* [Add armv7-unknown-linux-musleabi to release binaries](https://github.com/wcampbell0x2a/backhand/pull/543/commits/81be7917ef8cab80c6b3193050144104a37a74b5)
* [Add aarch64-unknown-linux-musl to binaries and testing](https://github.com/wcampbell0x2a/backhand/pull/543/commits/238c15553fcc4694824738fa29d9fbed1e0a2a4a)

Add armv7-unknown-linux-musleabi and aarch64-unknown-linux-musl releases

---

.github/workflows/main.yml
.github/workflows/msrv.yml
CHANGELOG.md
README.md
backhand-cli/Cargo.toml
backhand-cli/src/bin/add.rs
backhand-cli/src/bin/replace.rs
backhand-test/tests/add.rs
backhand-test/tests/replace.rs

* add: Move --out to positional, remove default added.squashfs
* replace: Move --out to positional, remove default replace.squashfs
* both: Use default tracing RUST_LOG and add more info/error output

cli: Add/Replace improvements

---

.github/workflows/main.yml
CHANGELOG.md
README.md

Continuation of https://github.com/wcampbell0x2a/backhand/pull/634, testing out some CI

Add Windows backhand support testing

---

.github/workflows/benchmark.yml
.github/workflows/binaries.yml
.github/workflows/coverage.yml
.github/workflows/labeler.yml
.github/workflows/main.yml
.github/workflows/msrv.yml
.github/workflows/pull_request.yml

Fixes:
* Error: The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15
* Warning: ubuntu-latest pipelines will use ubuntu-24.04 soon

Update CI build images

---

.github/workflows/main.yml
Cargo.lock
backhand-cli/Cargo.toml
backhand-test/Cargo.toml
backhand-test/tests/test.rs
backhand/Cargo.toml
backhand/src/compressor.rs

Rebased, Continuation of https://github.com/wcampbell0x2a/backhand/pull/701, with tests and backhand-test,backhand-cli support

Add lz4 compression and decompression

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
backhand-cli/Cargo.toml
backhand/src/lib.rs

rel: 0.21.0

---

Cargo.lock
backhand/Cargo.toml
backhand/src/compressor.rs

Closes https://github.com/wcampbell0x2a/backhand/issues/326

Use liblzma instead of xz2

---

BENCHMARK.md
bench.bash

Add --quick, to just do a compare against `squashfs-tools`.
TODO

Add --quick to bench

---

.github/workflows/coverage.yml
.github/workflows/main.yml
DEVELOPMENT.md
README.md
backhand-test/tests/test.rs
justfile

* Add justfile for ease of dev
* Use nextext for testing
* Use nextext for coverage

Switch to cargo nextest for testing and coverage
