- Cargo.toml
- lfs/test_04/out.squashfs
- lfs/test_04/testing/03
- lfs/test_04/testing/what/04
- lfs/test_04/testing/what/yikes/01
- lfs/test_04/testing/what/yikes/02
- lfs/test_04/testing/woah/05
- lfs/test_05/a/b/c/d
- lfs/test_05/out.squashfs
- src/lib.rs
- src/main.rs
- tests/test.rs
* Return filepath from extract_file
* Add tracing support for better debugging
* Add tests for new filepath
* Dir is now only deserialized during an inode lookup process. It is
stored by the API user as metadata blocks
> When extracting file, return it's full filepath

- src/compressor.rs
- src/dir.rs
- src/inode.rs
- src/lib.rs
- src/metadata.rs
- src/reader.rs
- src/squashfs.rs
- src/writer.rs
- tests/test.rs
* Squashfs::to_bytes(..) now supports and generates correct squashfs images that allow reading into our own struct in memory and then be able to compress the sections and write this to memory.
* Support 0xffff_ffff_ffff_ffff as a lookup table not existing and thus not read
> Fix to_bytes, test with real world squashfs image

- Cargo.toml
- README.md
- src/bin/unsquashfs.rs
- src/filesystem.rs
- src/reader.rs
- src/squashfs.rs
- src/tree.rs
- tests/test.rs
* Instead of iterating through the inodes, use a HashMap of all inode numbers and start at the inode recursively calling the directory reading function
> Rewrite into_filesystem to start at root_inode

- src/squashfs.rs
* Avoid overflow when calculating the inode offset from start offset
> Properly use inode_offset while still unsigned

- src/squashfs.rs
* When adding tail-end fragments to data, move to block_offset only within fragment bytes
> Fix adding tail-end fragments to data

- CHANGELOG.md
- src/compressor.rs
- src/data.rs
- src/entry.rs
- src/filesystem.rs
- src/metadata.rs
- src/squashfs.rs
* Use block_size for default compression dict size if compression options aren't present
* Store data uncompressed if compression doens't decrease size of data block
> Use block_size in default compression XZ

- README.md
- src/bin/add.rs
- src/bin/unsquashfs.rs
- src/data.rs
- src/filesystem.rs
- src/lib.rs
- src/squashfs.rs
- src/tree.rs
- tests/mutate.rs
This was the disadvantage of now allowing the `mut_file` function.
This function could be viable again if we use the `Any` trait and downcast it, but it is a kind of a hack.
> SquashfsFileWriter use dyn std::io::Read instead of Vec<u8>

- CHANGELOG.md
- src/filesystem.rs
- src/squashfs.rs
- tests/mutate.rs
Function required duplicated fields. Removed fields and simplified the push_symlink function.
> Fix push_symlink

- README.md
- benches/benchmark.rs
- src/bin/add.rs
- src/filesystem.rs
- src/lib.rs
- tests/mutate.rs
- tests/test.rs
The `FilesystemWriter::to_bytes` is impractical with very big files, because it require the output file to be completely be stored in ram.
I suggest to remove this api and instead suggest the use of `FilesystemWriter::write` and `FilesystemWriter::write_with_offset`.
> Remove the to_bytes api and replace it by write

- src/data.rs
- src/entry.rs
- src/filesystem.rs
- src/inode.rs
- src/metadata.rs
- src/reader.rs
- src/squashfs.rs
- src/tree.rs
This PR ended up being too big.
Now is possible to run https://github.com/wcampbell0x2a/backhand/pull/37.
The command `add airootfs.sfs empty-file /tmp`, takes around 6min and 1G of ram, but is at least possible.
The main memory saver is https://github.com/wcampbell0x2a/backhand/commit/3eb129d7eced3aa92a321715216e72643f548af4, that allow the buffered memory to be freed after the `FilesystemFileReader` is fully consumed.
But each commit saves few GB/MB of memory.
> Restructure FilesystemWriter::write

- README.md
- src/bin/add.rs
- src/bin/unsquashfs.rs
- src/entry.rs
- src/filesystem.rs
- src/fragment.rs
- src/inode.rs
- src/lib.rs
- src/squashfs.rs
- src/tree.rs
- tests/mutate.rs
- tests/test.rs
- All public API is defined within the lib.rs, with previous modules being hidden by default
- Rename FilesysteHeader into NodeHeader
> Define public api

- src/filesystem.rs
- src/lib.rs
Some types further down in the API weren't public, this makes them
public: FilesystemReaderFile and Node.
> Add some types to public API

- CHANGELOG.md
- Cargo.toml
- src/bin/add.rs
- src/error.rs
- src/filesystem.rs
- src/tree.rs
- tests/mutate.rs
- tests/raw.rs
- `FilesystemWriter::push_file(..)` correctly enters file into filesystem
- Remove Result return type from `FilesystemWriter::{push_file(..), push_dir(..), push_symlink(..), push_char_device(..) and push_block_devivce(..)`.
- Remove unused errors: `FieldNotInitialized` and `OsStringToStr`.
> Fix FilesystemWriter::push_file(..), Remove Return Types, Rel v0.9.0

- CHANGELOG.md
- src/filesystem.rs
- Around 9% improvement in read_only benchmarks
> Pass filesystem BlockFragment by reference

- src/dir.rs
- src/entry.rs
- src/filesystem/reader.rs
- src/filesystem/writer.rs
- src/fragment.rs
- src/inode.rs
- src/lib.rs
- src/metadata.rs
- src/reader.rs
- src/squashfs.rs
- src/tree.rs
- tests/non_standard.rs
- tests/raw.rs
- tests/test.rs
- Support non standard images. Read and Write!
- Add Kind for including endian and version information
- Add Kind: LE_V4_0 for linux kernel and upstream squashfs-tools support
- Add Kind: BE_V4_0 for custom vendor firmware
- Add Kind: AVM_BE_V4_0 for Fritz!OS firmware support. Added because it's interesting, as they kept some of it still BE.
- Change lookup table from u32 to u64. This was working in LE, but is
very wrong for LE!
See https://github.com/wcampbell0x2a/backhand/issues/72
> WIP: Support non-standard images

- CHANGELOG.md
- src/filesystem/writer.rs
- src/lib.rs
- src/squashfs.rs
- tests/raw.rs
- Add pad_len to FilesystemWriter, with public API set_kib_padding
- Test bytes_read and Superblock from write()
> Add set_kib_padding to FilesystemWriter

- src/filesystem/reader.rs
- Fix bug where blocks would be extracted as if extracting the first block
See #189
> Clear the data extraction buffer before decompressing more

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/bin/unsquashfs.rs
- Generate the same modes/permissions squashfs-tools/unsquashfs when running in user-mode and root
> Fix unsquashfs permission/mode extraction

- tests/bin.rs
This seemed to fix errors found in: https://github.com/wcampbell0x2a/backhand/pull/207 CI
> Fix testing with squashfs-tools/unsquashfs

- src/entry.rs
- src/filesystem.rs
- src/filesystem/node.rs
- src/filesystem/reader.rs
- src/filesystem/writer.rs
- src/squashfs.rs
This is one more step to lower the memory use for bug squashfs files. This probably don't have a huge effect on itself, but will probably allow future improvements.
> Flatten the nodes tree into a vec

- README.md
- src/bin/unsquashfs.rs
- This was accidentally removed during some merges into v0.12.0. The
README.md actually already has it in the example(with some wrong
spelling).
> unsquashfs: Show possible --kind values

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/unsquashfs.rs
- src/filesystem.rs
- tests/replace.rs
- tests/unsquashfs.rs
- Add --path-filter. For instance, when given "/usr/bin/", it will parse whatever files exist in "/usr/bin" such like "/usr/bin/*". It will also correctly put that file with the correct file permissions and modes for /, /usr/, and /usr/bin. If given an exact file, only return that file (with correct parent nodes)
See #234
> unsquashfs: Add --path-filter to limit extraction

- src/bin/unsquashfs.rs
- src/compressor.rs
- src/squashfs.rs
- tests/test.rs
- Support OpenWrt XZ custom compression options
- Enable output of these options during FilesystemWriter
See #72
> Add support for OpenWrt compression options

- src/bin/add.rs
- src/bin/unsquashfs.rs
- src/entry.rs
- src/filesystem/node.rs
- src/filesystem/writer.rs
- src/inode.rs
- src/squashfs.rs
- tests/add.rs
91a8e34 add: Read new file metadata from --file, force --dir
454cd8b backhand: Fix Uid and Gid adding to FilesystemWriter
1df1d83 add: Improve --help for dir
696e2b3 docs: Replace guid with gid
> add: Fix incorrect Gid and Uid creation

- .github/workflows/binaries.yml
- CHANGELOG.md
- Cargo.toml
* Add LTO: This doesn't increase performance by a measurable amount. The compression algorithms need looked into to enable in their build system.
* Add stripped binaries for dist releases from ci
> ci: Use new dist profile for release binaries

- CHANGELOG.md
- src/filesystem/writer.rs
- tests/issues.rs
* Use Id::root() when creating an empty FilesystemWriter, so that the 0 index that is also added from a node will be unwrapped correctly later
> backhand: Fix FilesystemWriter::default() empty generation

- CHANGELOG.md
- src/filesystem/reader.rs
* Remove manual Clone impl for FilesystemReaderFile.
* See: https://rust-lang.github.io/rust-clippy/master/index.html#/incorrect_clone_impl_on_copy_type
>  If both Clone and Copy are implemented, they must agree.
> This is done by dereferencing self in Clone’s implementation.
> Anything else is incorrect.
> backhand: Fix clippy::incorrect_clone_impl_on_copy_type

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/bin/unsquashfs.rs
- tests/unsquashfs.rs
* Add progress bar to show the progress of the currently extraced files. Two other spinner progress bars are for magic finding and start/end of image read. This can easily be extended when multi-threading becomes a thing for this program.
* Add --quiet, for not showing progress bar output and RUST_LOG output
> unsquashfs: Add progress bar

- .rustfmt.toml
- src/bin/unsquashfs.rs
- src/compressor.rs
- src/data.rs
- src/entry.rs
- src/filesystem/node.rs
- src/filesystem/reader.rs
- src/filesystem/writer.rs
- src/fragment.rs
- src/inode.rs
- src/kinds.rs
- src/metadata.rs
- src/squashfs.rs
- tests/add.rs
- tests/mutate.rs
- tests/non_standard.rs
- tests/raw.rs
- tests/replace.rs
- tests/test.rs
- tests/unsquashfs.rs
- This fixes many of my own complaints about cargo fmt
> fmt: Add use_small_heuristics config option

- .github/workflows/coverage.yml
- This runs the binaries, so this speeds up the CI by a large amount
> ci: Use --release for coverage test

- backhand-test/tests/issues.rs
- backhand/src/filesystem/writer.rs
> Fix issue 359, missing uid/gid

- backhand-test/tests/issues.rs
- backhand/src/filesystem/node.rs
> Fix issue 363

- .github/workflows/binaries.yml
- CHANGELOG.md
Remove, as mips has joined the crypt as tier 3 only: https://github.com/rust-lang/rust/pull/115238/ as of https://github.com/rust-lang/rust/releases/tag/1.75.0
> Remove mips from ci and release builds

- .github/workflows/pull_request.yml
Add hopeful fix for triggering CI on auto-commit push. See https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
> ci: Use PAT token for changelog-auto-commit

- Cross.toml
- backhand-test/tests/non_standard.rs
Fix bug in TEST_PATH that was causing a racey test with another test *also* writing to the same result file.
> Fix spurious CI: Add RUST_LOG to cross tests

- .github/workflows/binaries.yml
- .github/workflows/coverage.yml
- .github/workflows/main.yml
- BENCHMARK.md
- CHANGELOG.md
- Cargo.lock
- backhand-cli/Cargo.toml
- backhand-test/Cargo.toml
- backhand-test/tests/test.rs
- backhand/Cargo.toml
- backhand/src/compressor.rs
- bench.bash
* Add zune-inflate: "This crate features an optimized inflate algorithm supporting whole buffer decompression."
* Add another benchmark target with `-musl` since we gain some speedup
> Add gzip-zune-inflate feature

- backhand/src/reader.rs
- backhand/src/squashfs.rs
Parse root_inode inside of inodes() to save memory and CPU cycles
Rename private dir_blocks into uncompressed_metadatas
> Cleanup/Remove root_inode

- backhand-cli/src/bin/unsquashfs.rs
- backhand/src/entry.rs
- backhand/src/filesystem/node.rs
- backhand/src/filesystem/reader.rs
- backhand/src/filesystem/writer.rs
- backhand/src/inode.rs
- backhand/src/squashfs.rs
I stumbled across a file with named pipe nodes which made `unsquashfs-backhand` panic.
This is my attempt at adding support for named pipes. It is currently missing tests. But I could already extract a private squashfs image containing named pipes.
The redistributable public test file I found contains socket nodes (at least according to the error message I got), so using it as a testcase would require to also implement at least the socket nodes.
A relevant test file from unblob project:
https://github.com/onekey-sec/unblob/blob/0dc4bb53b30b1723245604947669e6817c82de97/tests/integration/filesystem/squashfs/squashfs_v4_le/__input__/squashfs_v4.specfile.bin
> Add named pipe (fifo) handling

- backhand/src/filesystem/reader.rs
This is only one call, but might be more in the future
> reader: Reduce file.system.reader.lock() lifetime

- .github/workflows/binaries.yml
- .github/workflows/coverage.yml
- .github/workflows/main.yml
- .github/workflows/msrv.yml
- BENCHMARK.md
- Cargo.lock
- Cross.toml
- backhand-cli/src/bin/unsquashfs.rs
- backhand-test/tests/add.rs
- backhand-test/tests/test.rs
- backhand/Cargo.toml
- backhand/src/compressor.rs
- backhand/src/data.rs
- backhand/src/filesystem/reader.rs
- backhand/src/reader.rs
- backhand/src/squashfs.rs
- bench.bash
- [backhand: Use RwLock for fragment cache](https://github.com/wcampbell0x2a/backhand/pull/504/commits/724c8c259dd76db8bc057f8d24b408bcce0d0785)
- [reader: Reduce copy_from_slice fragment amount](https://github.com/wcampbell0x2a/backhand/pull/504/commits/0a50fb24a4bd28fac2587e9d692f40bb0aeac93e)
- [unsquashfs: Add BufReader and BufWriter to io](https://github.com/wcampbell0x2a/backhand/pull/504/commits/0ac5b53b434d8a63e96aa2f89794718b539bfd1e)
> backhand: Improve performance

- .github/workflows/msrv.yml
- backhand-cli/Cargo.toml
- backhand-cli/src/lib.rs
- backhand/Cargo.toml
- backhand/src/compressor.rs
- backhand/src/lib.rs
* Fix bug in --help to correctly show support for gzip. Previously it would not show the correct help when gzip-zune-inflate was selected
* gzip and gzip-zune-inflate will give a compile-time error when selected together
> Add any-gzip feature

- Cargo.lock
- backhand-test/tests/raw.rs
- backhand/Cargo.toml
- backhand/src/data.rs
- backhand/src/filesystem/writer.rs
- backhand/src/lib.rs
- backhand/src/reader.rs
- backhand/src/squashfs.rs
* Add cache to DataWriter, that if enabled will remember the file length and a hash of a previous file and use that instead of writing the matching file to disk.
* Add set_no_duplicate_files to FilesystemWriter to make this configurable.
* Make superblock Flags public
- Maybe hash the first 32 bytes to do a quick comparison, before hashing the entire file
- cleanup code quality
-  Add test that adds a file that already exists, should be the same size? (might want to check that just_copy_it, works)
- Use https://github.com/paritytech/nohash-hasher (some other hashes I use could use this!)
> backhand: Remove duplicate data

- backhand-cli/src/bin/unsquashfs.rs
- backhand-test/tests/unsquashfs.rs
- backhand/src/filesystem/reader.rs
- backhand/src/filesystem/writer.rs
- backhand/src/squashfs.rs
* When using binaries such as add, or mutate the deduplicatin setting should be used that was read from the reader if we can
> backhand: Data duplication flag should be kept from reader

- .github/workflows/binaries.yml
- BENCHMARK.md
- CHANGELOG.md
- Cargo.lock
- backhand/Cargo.toml
- bench.bash
* libz-sys now allows to build from cc instead of cmake. This patch enables this
for the flate2 crate, which should be the fastest implementation of gzip
* Update LAST_RELEASE to v0.18.0
* Use libz-sys instead of gzip-zune-inflate when building release binaries
```
Old(gzip-zune-inflate):
Benchmark 2: backhand-dist
Time (mean ± σ):     804.6 ms ±  12.8 ms    [User: 1047.7 ms, System: 267.5 ms]
Range (min … max):   771.8 ms … 837.3 ms    50 runs
Benchmark 3: backhand-dist-musl
Time (mean ± σ):      1.399 s ±  0.019 s    [User: 1.903 s, System: 0.330 s]
Range (min … max):    1.358 s …  1.442 s    50 runs
New(flate::libz-sys):
Benchmark 2: backhand-dist
Time (mean ± σ):     672.0 ms ±   5.9 ms    [User: 846.2 ms, System: 217.1 ms]
Range (min … max):   659.2 ms … 693.9 ms    50 runs
Benchmark …
```
> Enable libz sys for flate2

- CHANGELOG.md
- README.md
- backhand-cli/src/bin/add.rs
- backhand-cli/src/bin/replace.rs
- backhand-test/tests/add.rs
- backhand-test/tests/non_standard.rs
- backhand/src/compressor.rs
- backhand/src/filesystem/writer.rs
- backhand/src/kinds.rs
* You ever wonder "what if a squashfs had custom compression options that I am forced to emit because the kernel is expecting this?". If this is you, then have fun with this addition! This allows one to implement compression_options for CompressionAction and emit.. whatever you want as the the compression option bytes.
* Change superblock struct in FilesystemWriter As Soon As Possible to make sure everything can just use those settings.
* Update tests to be un-padded for custom compression, easier to see the diff's with biodiff and such.
> Add non-standard CompressionOptions support

- CHANGELOG.md
- backhand-test/tests/test.rs
- backhand/src/filesystem/reader.rs
Closes https://github.com/wcampbell0x2a/backhand/issues/609
> Support sparse files

- .gitignore
- flake.lock
- flake.nix
- rust-toolchain.toml
This PR provides `rust-toolchain.toml` to fix the toolchain used for builds, which is a nice thing to have for replicable builds. Moreover, it adds `flake.nix` for nix users that can be used to use the project directly, and to contribute.
> Add nix flake and rust toolchain

- CHANGELOG.md
- backhand-cli/src/bin/unsquashfs.rs
- backhand-test/tests/non_standard.rs
- backhand/src/data.rs
- backhand/src/filesystem/node.rs
- backhand/src/filesystem/reader.rs
- backhand/src/filesystem/writer.rs
- backhand/src/inode.rs
- backhand/src/squashfs.rs
* This "check" was incorrect, and is over limiting the amount of dirs that _could_ be read. This was added to prevent over-allocing, but is now removed since it's incorrect.
Closes #690
> Remove check for ExtendedDirectory index count

- .github/workflows/coverage.yml
- .github/workflows/main.yml
- Cargo.lock
- backhand-cli/Cargo.toml
- backhand-test/Cargo.toml
- backhand-test/tests/test.rs
- backhand/Cargo.toml
- bench.bash
The usage of zune-inflate was already remove, this removes from Cargo.toml
and other references
> Update flate2 with zlib-rs as default

- Cargo.lock
- backhand/Cargo.toml
* With our use of flate zlib-rs, we don't have a use for libz-sys
Closes #702
> Remove libz-sys

- backhand/src/compressor.rs
- backhand/src/inode.rs
The underlying issue is https://github.com/sharksforarms/deku/issues/552. Adding `#[repr(u16)]` works around the problem.
> Avoid misaligned pointer loads with Deku and id_type = u16
